Set objBrowser = Description.Create()
		objBrowser("micClass").value = "Browser"
Set objPage = Description.Create()
		objPage("micClass").value = "Page"
Set objName = Description.Create()
		objName("name").value = "username"
Set objPwd = Description.Create()
		objPwd("name").value = "userpwd"
Set objBtn = Description.Create()
		objBtn("name").value = "µÇÂ¼"
Set objSignout = Description.Create()
		objSignout("text").value = "ÍË³ö"