Set objFavourable  = Description.Create()
		objFavourable("test").value = "优惠管理"
Set objAdd  = Description.Create()
		objAdd("test").value = "添加优惠"
Set objId  = Description.Create()
		objId("type").value = "id"
Set objYprice = Description.Create()
		objYprice("type").value = "Yprice"
Set objBtn  = Description.Create()
		objBtn("type").value = "Submit"